### ISSUE TITLE
[Android] Error while updating property 'd' in shadow node of type: RNSVGPath

### ISSUE THREAD

**Issue by fdnhkj** [bgryszko/react-native-circular-slider#2] opened 2016-12-31 00:22 UTC
I tried the example app in Android (copy `index.ios.js` & paste into `index.android.js`) and after touching the slider it throws an error described below.
![circular-slider](https://cloud.githubusercontent.com/assets/5569608/21574620/6efa8356-cef6-11e6-9363-b2bb636b2d9d.gif)

> Error while updating property 'd' in shadow node of type: RNSVGPath
updateShadowNodeProp
    ViewManagersPropertyCache.java:110
setProperty
    ViewManagerPropertyUpdater.java:148
updateProps
    ViewManagerPropertyUpdater.java:52
updateProperties
    ReactShadowNode.java:246
updateView
    UIImplementation.java:216
updateView
    UIManagerModule.java:245
invoke
    Method.java:-2
invoke
    BaseJavaModule.java:318
invoke
    JavaModuleWrapper.java:158
run
    NativeRunnable.java:-2
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:148
run
    MessageQueueThreadImpl.java:196
run
    Thread.java:818

**Comment by bozzmob** [comment] 2016-12-31 07:44
I'm having the same issue. The slider doesn't slide.

**Comment by brentvatne** [comment] 2016-12-31 17:25
cc @magicismight

**Comment by bgryszko** [comment] 2016-12-31 18:54
I think the issue is not in the react-native-svg - looks like measuring works differently on the android. I'll take closer look in 2017 😉 Happy New Year guys! 🎉

**Comment by bgryszko** [comment] 2017-01-07 08:15
OK, got it fixed in f219ae8!

**Closed by bgryszko** 2017-01-07 08:15 UTC
